### ISSUE TITLE
adc.md seems useless

### ISSUE THREAD

**Issue by thirschbuechler** [MyTooliT/Documentation#1]
[adc.md](https://github.com/MyTooliT/Documentation/blob/master/ADC/ADC.md) (https://github.com/MyTooliT/Documentation/commit/2b1c6283b5b505ba7bd5bb5851f6e1a27b734cfb)

was done by me i think, however it seems incoherent and badly documented.Maybe Walthers' doc refers to this, maybe not
[Commands.md](https://github.com/MyTooliT/Protocol/blob/master/Commands.md)

**Comment by sanssecours** [comment]
👋 Hi Thomas,

if you think that the information in that part of the documentation is not useful, then we can of course remove it. As far as I know no other part of the text refers to it. This means we only need do delete the file and the entry for it in the [bookdown config](https://github.com/MyTooliT/Documentation/blob/cd4e702d9d0eb1e98486bde5dbf7eb352b35c4e7/_bookdown.yml#L10), if you wan to get rid of it. I do leave that decision up to you though 😊. If you do not want to include the file, then you can just delete it from the repo or I can do it for you if you like? Since the text does not seem to contain misleading information, I would just leave it as it is for now.

**Comment by thirschbuechler** [comment]
dunno, ok lets leave it for now (file&issue)
